### PR TITLE
Add tests for QuantityValue::newFromArray

### PR DESCRIPTION
**Pull request by thiemowmde**
Split from #66. Pinging @brightbyte again.

### CODE REVIEW

**Comment by brightbyte** [comment]
Will need to change quite a bit once UnboundedQuantityValue is introduced.

**Comment by thiemowmde** [comment]
Not sure what you mean. This is an untouched copy from the code currently in #66, except for one removed test case.

**Comment by brightbyte** [comment]
I just merged UnboundedQuantityValue. Can you update this to add all the newFromArray tests now, for both classes?

**Comment by thiemowmde** [comment]
This is already the case. As said, only a single test case from #66 is missing at the moment, because QuantityValue is still in a state where it behaves exactly like before. I did added that test case for now, see the 2nd commit.

**Pull request merged**
